image: jakzal/phpqa:php8.1

default:
  before_script:
    - composer install

  cache:
    paths:
    - vendor/

stages:
  - UnitTests

phpunit:
  stage: UnitTests
  script:
  - ./vendor/bin/phpunit --ignore-platform-req
